# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to ECR

on:
 
  push:
    branches: [ main , dev]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
 
    steps:

    - name: Check out code
      uses: actions/checkout@v3
    - name: Check Node v # Node v 확인
      run: node -v

    - name: Install Dependencies # 의존 파일 설치
      run: npm install 
      
    - name: Build # React Build
      run: npm run build
      env:
          CI: ""
    - name: zip create
    
      run: zip -qq -r ./build-fe.zip .
      shell: bash
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3 # Upload build file to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://cicdpeernow/build-fe.zip
        
    - name: Deploy # Deploy to EC2
      run: aws deploy create-deployment
        --application-name PNdeploy
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name PNGP
        --s3-location bucket=cicdpeernow,key=build-fe.zip,bundleType=zip
